import { chromium } from '@playwright/test';
import { readdir } from 'node:fs/promises';
import { join } from 'node:path';
import assert from 'node:assert/strict';
const cache=join(process.env.LOCALAPPDATA,'ms-playwright');
const builds=(await readdir(cache)).filter(s=>/^chromium-\d+$/.test(s)).sort((a,b)=>Number(b.split('-')[1])-Number(a.split('-')[1]));
const browser=await chromium.launch({headless:true,executablePath:join(cache,builds[0],'chrome-win64/chrome.exe')});
try {
  const page=await browser.newPage({reducedMotion:'reduce'});
  const errors=[], wasm=[];
  page.on('pageerror',error=>errors.push(String(error)));
  page.on('response',response=>{if(response.url().endsWith('.wasm'))wasm.push({url:response.url(),status:response.status(),type:response.headers()['content-type']});});
  await page.goto('http://127.0.0.1:4175/');
  await page.waitForFunction(()=>window.angouri?.state);
  assert.equal(await page.locator('#share-open').isVisible(),false);
  assert.equal(await page.locator('[data-op="H"] .katex').count(),1);
  await page.locator('[data-op="H"]').click();
  await page.waitForFunction(()=>window.angouri.result.solved);
  await page.locator('#launch').click();
  await page.waitForFunction(()=>window.angouri.flight.phase==='landed');
  assert.equal(await page.locator('#launch').textContent(),'Next puzzle');
  assert.equal(await page.locator('.game-shell.intro').count(),1);
  assert.equal(await page.locator('.pipeline[aria-label="Recipe, 1 of 1 slots filled"]').count(),1);
  assert.equal(await page.locator('.construction').isVisible(),false);
  assert(wasm.length>0);
  assert(wasm.every(r=>r.status===200&&r.type==='application/wasm'));
  await page.goto('http://127.0.0.1:4175/about/');
  assert((await page.locator('body').textContent()).includes('AngouriMath'));
  await page.getByRole('link',{name:'Back to the playground'}).click();
  await page.waitForFunction(()=>window.angouri?.result?.solved);
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({stagedRoot:'passed',wasmResources:wasm.length,wasmMime:'application/wasm',about:'passed',restoredProgress:'passed',pageErrors:errors},null,2));
} finally {await browser.close();}
